// ===== 11大模块Schema定义 =====
const SCHEMAS = {
  archive: {
    id: 'archive',
    name: '作品入库档案库',
    icon: '📦',
    color: '#7b5fa8',
    bg: '#f3eef9',
    modClass: 'mod-archive',
    category: '核心创作',
    desc: '归档所有爆款范文、仿写稿、个人完稿、拆文稿',
    fields: [
      { key: 'title', label: '作品名', type: 'text', required: true, full: true, ph: '如：《婆婆的退休金去哪了》' },
      { key: 'platform', label: '首发平台', type: 'select', options: ['知乎','番茄','小程序','七猫','其他'] },
      { key: 'genre', label: '题材赛道', type: 'select', options: ['婚内打脸','婆媳家庭','真假千金','重生纠错','校园恩怨','职场逆袭','原生家庭','微悬疑吃瓜','都市猎奇','古风短虐'] },
      { key: 'wordCount', label: '总字数', type: 'number', ph: '如：9500' },
      { key: 'sectionCount', label: '分节数量', type: 'number', ph: '如：12' },
      { key: 'corePlot', label: '核心剧情梗', type: 'textarea', full: true, ph: '一句话概括核心冲突和反转' },
      { key: 'performance', label: '数据表现', type: 'textarea', full: true, ph: '如：阅读12万+，点赞3800，完读率45%' },
      { key: 'adaptScene', label: '适配仿写场景', type: 'textarea', full: true, ph: '适合用在哪类仿写场景' },
    ],
    cardTitle: 'title',
    cardTags: ['platform','genre'],
    cardBody: ['corePlot','performance','adaptScene'],
    filterField: 'genre',
    filterLabel: '赛道',
  },

  openings: {
    id: 'openings',
    name: '开篇钩子库',
    icon: '🪝',
    color: '#4f7ec8',
    bg: '#e8f0fc',
    modClass: 'mod-openings',
    category: '核心创作',
    desc: '知乎提问式 / 小程序悬念式 / 番茄冲突式开篇模板',
    fields: [
      { key: 'type', label: '开篇类型', type: 'select', options: ['知乎提问式','小程序悬念式','番茄冲突式'], required: true },
      { key: 'title', label: '模板名称', type: 'text', required: true, full: true, ph: '如：婆媳矛盾·养老金追问式开篇' },
      { key: 'formula300', label: '开篇300字留人公式', type: 'textarea', full: true, ph: '300字开篇结构拆解：钩子→悬念→情绪锚点→留人' },
      { key: 'hookTemplate', label: '首屏钩子模板', type: 'textarea', full: true, ph: '可直接套用的首屏第一句/第一段模板' },
      { key: 'prosCons', label: '开篇优缺点拆解', type: 'textarea', full: true, ph: '这个开篇的优点和缺点分析' },
      { key: 'avoidList', label: '开篇避雷清单', type: 'textarea', full: true, ph: '使用此开篇需要注意的雷区' },
    ],
    cardTitle: 'title',
    cardTags: ['type'],
    cardBody: ['formula300','hookTemplate'],
    filterField: 'type',
    filterLabel: '类型',
  },

  topics: {
    id: 'topics',
    name: '赛道选题库',
    icon: '🎯',
    color: '#4f9b6b',
    bg: '#e8f5ee',
    modClass: 'mod-topics',
    category: '核心创作',
    desc: '10大流量赛道的爆款公式与核心冲突模板',
    fields: [
      { key: 'track', label: '赛道名称', type: 'select', options: ['婚内打脸','婆媳家庭','真假千金','重生纠错','校园恩怨','职场逆袭','原生家庭','微悬疑吃瓜','都市猎奇','古风短虐'], required: true },
      { key: 'title', label: '选题名称', type: 'text', required: true, full: true, ph: '如：婆婆偏心小叔子·退休金争夺战' },
      { key: 'formula', label: '爆款公式', type: 'textarea', full: true, ph: '此赛道的爆款结构公式' },
      { key: 'conflictTpl', label: '核心冲突模板', type: 'textarea', full: true, ph: '可复用的核心冲突设计' },
      { key: 'plots', label: '高频剧情', type: 'textarea', full: true, ph: '此赛道高频出现的剧情走向' },
      { key: 'ideas', label: '可写选题', type: 'textarea', full: true, ph: '基于此赛道可写的选题列表' },
      { key: 'painPoints', label: '受众情绪痛点', type: 'textarea', full: true, ph: '此赛道读者的情绪爽点和痛点' },
    ],
    cardTitle: 'title',
    cardTags: ['track'],
    cardBody: ['formula','conflictTpl','painPoints'],
    filterField: 'track',
    filterLabel: '赛道',
  },

  characters: {
    id: 'characters',
    name: '人设素材库',
    icon: '👤',
    color: '#c86b95',
    bg: '#fce8f0',
    modClass: 'mod-characters',
    category: '核心创作',
    desc: '万字短篇轻量化人设模板与避雷指南',
    fields: [
      { key: 'type', label: '人设类型', type: 'select', options: ['飒爽清醒女主','隐忍逆袭主角','伪善白月光','道德绑架长辈','凤凰男/扶弟魔','偏执男主','功能性配角'], required: true },
      { key: 'name', label: '人设名称/代号', type: 'text', required: true, full: true, ph: '如：清醒型女主A版·不内耗不圣母' },
      { key: 'surface', label: '表层人设', type: 'textarea', full: true, ph: '外在表现：言行举止、给读者的第一印象' },
      { key: 'deep', label: '深层人设', type: 'textarea', full: true, ph: '内在驱动：真实动机、性格内核' },
      { key: 'contrast', label: '反差设计', type: 'textarea', full: true, ph: '表里反差、前后转变的设计' },
      { key: 'entrance', label: '出场方式', type: 'textarea', full: true, ph: '最佳出场场景和方式设计' },
      { key: 'function', label: '人物功能', type: 'textarea', full: true, ph: '此角色在故事中承担的叙事功能' },
      { key: 'avoidPoints', label: '人设避雷点', type: 'textarea', full: true, ph: '写此角色需要避开的雷区' },
    ],
    cardTitle: 'name',
    cardTags: ['type'],
    cardBody: ['surface','deep','contrast','function'],
    filterField: 'type',
    filterLabel: '人设类型',
  },

  structure: {
    id: 'structure',
    name: '剧情结构库',
    icon: '📐',
    color: '#4f9b9b',
    bg: '#e8f5f5',
    modClass: 'mod-structure',
    category: '核心创作',
    desc: '8000-12000字标准框架与逐节节奏规范',
    fields: [
      { key: 'title', label: '结构名称', type: 'text', required: true, full: true, ph: '如：万字三幕式·12节标准框架' },
      { key: 'structureType', label: '结构类型', type: 'select', options: ['三幕式','四幕式','五幕式','线性递进','多线交织'] },
      { key: 'wordRange', label: '适用字数范围', type: 'text', ph: '如：8000-12000字' },
      { key: 'ratio', label: '字数配比', type: 'textarea', full: true, ph: '各幕/各节字数分配比例' },
      { key: 'rhythm', label: '逐节节奏规范', type: 'textarea', full: true, ph: '每节：独立冲突+节末悬念的详细规范' },
      { key: 'foreshadow', label: '伏笔埋收技巧', type: 'textarea', full: true, ph: '前埋后收的伏笔设计方法' },
      { key: 'reversal', label: '反转频次公式', type: 'textarea', full: true, ph: '反转出现的频次和节奏公式' },
      { key: 'emotionCurve', label: '情绪曲线', type: 'textarea', full: true, ph: '憋屈→拉扯→爆发→打脸→收尾的节奏设计' },
    ],
    cardTitle: 'title',
    cardTags: ['structureType','wordRange'],
    cardBody: ['ratio','rhythm','emotionCurve'],
    filterField: 'structureType',
    filterLabel: '结构',
  },

  analysis: {
    id: 'analysis',
    name: '拆文复盘库',
    icon: '🔍',
    color: '#8b5fc8',
    bg: '#f0e8fc',
    modClass: 'mod-analysis',
    hasAssistant: true,
    category: '复盘提升',
    desc: '统一拆文模板，所有拆解永久存档入库',
    fields: [
      { key: 'title', label: '拆文作品名', type: 'text', required: true, full: true, ph: '被拆解的作品名称' },
      { key: 'platform', label: '首发平台', type: 'select', options: ['知乎','番茄','小程序','七猫','其他'] },
      { key: 'genre', label: '题材赛道', type: 'select', options: ['婚内打脸','婆媳家庭','真假千金','重生纠错','校园恩怨','职场逆袭','原生家庭','微悬疑吃瓜','都市猎奇','古风短虐'] },
      { key: 'mainPlot', label: '核心大梗+辅助小梗', type: 'textarea', full: true, ph: '大梗：主线核心；小梗：辅助推进的剧情梗' },
      { key: 'conflict', label: '主线冲突', type: 'textarea', full: true, ph: '贯穿全文的核心矛盾' },
      { key: 'hooks', label: '钩子分布', type: 'textarea', full: true, ph: '各章节钩子放置位置和类型' },
      { key: 'climax', label: '高能爽虐点', type: 'textarea', full: true, ph: '全文最高能的爽点和虐点' },
      { key: 'rhythmReview', label: '节奏优缺点', type: 'textarea', full: true, ph: '节奏安排的优点和不足' },
      { key: 'logicHoles', label: '逻辑漏洞', type: 'textarea', full: true, ph: '发现的逻辑硬伤和修复建议' },
      { key: 'viralReason', label: '爆火归因', type: 'textarea', full: true, ph: '为什么会爆？核心因素分析' },
      { key: 'adaptPlan', label: '对标仿写方案', type: 'textarea', full: true, ph: '如何对标此文的仿写方案' },
      { key: 'rewrite', label: '换汤不换药改写思路', type: 'textarea', full: true, ph: '保留骨架、更换设定的改写思路' },
    ],
    cardTitle: 'title',
    cardTags: ['platform','genre'],
    cardBody: ['mainPlot','viralReason','adaptPlan'],
    filterField: 'genre',
    filterLabel: '赛道',
  },

  quotes: {
    id: 'quotes',
    name: '金句&对话库',
    icon: '💬',
    color: '#c88b5f',
    bg: '#fceee8',
    modClass: 'mod-quotes',
    category: '复盘提升',
    desc: '分类储存开篇、拉扯、打脸、反转、结尾金句',
    fields: [
      { key: 'category', label: '分类', type: 'select', options: ['开篇抓人金句','情绪拉扯短句','对峙打脸对话','反转点睛金句','结尾收口金句'], required: true },
      { key: 'content', label: '内容', type: 'textarea', required: true, full: true, ph: '金句或对话的完整内容' },
      { key: 'scene', label: '适用场景', type: 'text', full: true, ph: '如：婆媳对峙、女主打脸、结尾收束' },
      { key: 'tags', label: '标签', type: 'tags', full: true, ph: '输入后回车添加标签' },
      { key: 'notes', label: '备注', type: 'textarea', full: true, ph: '使用说明或改写建议' },
    ],
    cardTitle: 'content',
    cardTags: ['category'],
    cardBody: ['scene','notes'],
    filterField: 'category',
    filterLabel: '分类',
    cardRaw: true,
  },

  endings: {
    id: 'endings',
    name: '结局模板库',
    icon: '🎬',
    color: '#4f9b7b',
    bg: '#e8f5f0',
    modClass: 'mod-endings',
    category: '复盘提升',
    desc: '全品类结局模板与收尾规范、避雷清单',
    fields: [
      { key: 'type', label: '结局类型', type: 'select', options: ['爽文打脸结局','遗憾留白结局','双向救赎结局','悬疑真相结局'], required: true },
      { key: 'title', label: '模板名称', type: 'text', required: true, full: true, ph: '如：打脸式·当众揭穿型结局' },
      { key: 'template', label: '模板内容', type: 'textarea', full: true, ph: '结局的完整模板和结构' },
      { key: 'fastEnd', label: '极速收尾规范', type: 'textarea', full: true, ph: '万字短篇如何在最后500-1000字极速收尾' },
      { key: 'avoidList', label: '烂尾避雷清单', type: 'textarea', full: true, ph: '容易导致烂尾的写法和避雷要点' },
      { key: 'callback', label: '伏笔全回收技巧', type: 'textarea', full: true, ph: '结局回收前文伏笔的方法和技巧' },
    ],
    cardTitle: 'title',
    cardTags: ['type'],
    cardBody: ['template','fastEnd','avoidList'],
    filterField: 'type',
    filterLabel: '类型',
  },

  compliance: {
    id: 'compliance',
    name: '平台合规库',
    icon: '🛡️',
    color: '#4f68c8',
    bg: '#e8edfc',
    modClass: 'mod-compliance',
    category: '复盘提升',
    desc: '分平台收录审核红线、限流雷区、自查清单',
    fields: [
      { key: 'platform', label: '平台', type: 'select', options: ['知乎','番茄','小程序','七猫','通用'], required: true },
      { key: 'title', label: '条目名称', type: 'text', required: true, full: true, ph: '如：知乎·婆媳类敏感剧情避雷' },
      { key: 'redLines', label: '审核红线', type: 'textarea', full: true, ph: '绝对不能碰的内容红线' },
      { key: 'taboo', label: '敏感禁忌剧情', type: 'textarea', full: true, ph: '会导致审核不通过或限流的剧情类型' },
      { key: 'limitTraps', label: '限流雷区', type: 'textarea', full: true, ph: '会被算法限流的写法和内容' },
      { key: 'retention', label: '完读率优化技巧', type: 'textarea', full: true, ph: '提升完读率的实操技巧' },
      { key: 'checklist', label: '成品自查清单', type: 'textarea', full: true, ph: '发布前的逐条自查清单' },
      { key: 'caseStudy', label: '拒稿改稿对比案例', type: 'textarea', full: true, ph: '拒稿原文 vs 修改后通过的对比' },
    ],
    cardTitle: 'title',
    cardTags: ['platform'],
    cardBody: ['redLines','taboo','checklist'],
    filterField: 'platform',
    filterLabel: '平台',
  },

  conflicts: {
    id: 'conflicts',
    name: '冲突素材库',
    icon: '⚡',
    color: '#c86b6b',
    bg: '#fce8e8',
    modClass: 'mod-conflicts',
    category: '素材储备',
    desc: '日常可复用冲突素材，避免剧情空洞',
    fields: [
      { key: 'type', label: '素材类型', type: 'select', options: ['高频误会桥段','家庭矛盾','职场矛盾','邻里矛盾','心理细节','氛围场景','情绪拉扯片段'], required: true },
      { key: 'title', label: '素材名称', type: 'text', required: true, full: true, ph: '如：婆婆偷翻儿媳抽屉被发现' },
      { key: 'content', label: '内容描述', type: 'textarea', full: true, ph: '素材的详细内容描述' },
      { key: 'scene', label: '适用场景', type: 'text', full: true, ph: '可用在什么类型的作品中' },
      { key: 'tags', label: '标签', type: 'tags', full: true, ph: '输入后回车添加标签' },
      { key: 'notes', label: '备注', type: 'textarea', full: true, ph: '使用建议或改写提示' },
    ],
    cardTitle: 'title',
    cardTags: ['type'],
    cardBody: ['content','scene'],
    filterField: 'type',
    filterLabel: '类型',
  },

  hotspots: {
    id: 'hotspots',
    name: '每日热点转化库',
    icon: '🔥',
    color: '#c86b95',
    bg: '#fce8f0',
    modClass: 'mod-hotspots',
    hasFetch: true,
    category: '自动任务',
    desc: '每日自动抓取全网热点并转化为小说可用素材',
    fields: [
      { key: 'subCategory', label: '子分类', type: 'select', options: ['当日热点日报','历史热点存档','热点改编示范','热点避雷清单'], required: true },
      { key: 'title', label: '热点标题', type: 'text', required: true, full: true, ph: '热点事件标题' },
      { key: 'source', label: '来源', type: 'select', options: ['微博','知乎','头条','抖音','其他'] },
      { key: 'sourceLink', label: '原文/原视频链接', type: 'text', full: true, ph: '粘贴原文链接或视频链接，方便直接点击查看' },
      { key: 'fullText', label: '热点完整文字版', type: 'textarea', full: true, ph: '热点新闻的完整文字内容，方便直接阅读和提取素材' },
      { key: 'summary', label: '1.热点精简梗概', type: 'textarea', full: true, ph: '100字以内精简概述热点事件' },
      { key: 'emotionTag', label: '2.赛道情绪标签', type: 'text', full: true, ph: '如：愤怒、不甘、打脸、爽感' },
      { key: 'conflict', label: '3.核心戏剧冲突', type: 'textarea', full: true, ph: '提炼出的核心戏剧冲突' },
      { key: 'novelCore', label: '4.可直接使用的小说核心梗', type: 'textarea', full: true, ph: '可直接套用的核心剧情梗' },
      { key: 'adaptTrack', label: '5.适配写作赛道', type: 'select', options: ['婚内打脸','婆媳家庭','真假千金','重生纠错','校园恩怨','职场逆袭','原生家庭','微悬疑吃瓜','都市猎奇','古风短虐'] },
      { key: 'titleTemplates', label: '6.三个平台爆款标题模板', type: 'textarea', full: true, ph: '知乎/番茄/小程序各一个标题模板' },
    ],
    cardTitle: 'title',
    cardTags: ['subCategory','source','adaptTrack'],
    cardBody: ['summary','conflict','novelCore','fullText','titleTemplates'],
    cardLink: 'sourceLink',
    filterField: 'subCategory',
    filterLabel: '子分类',
    cardClass: 'hotspot-card',
  },
};

// ===== 预置示例数据 =====
const DEMO_DATA = {
  archive: [
    {
      id: 'd1', title: '婆婆的退休金去哪了', platform: '知乎', genre: '婆媳家庭',
      wordCount: 9500, sectionCount: 12,
      corePlot: '婆婆每月退休金4800，却说钱花光了。儿媳追查发现全给了小叔子还赌债，最终当众对峙打脸，婆婆醒悟。',
      performance: '阅读18万+，赞同4200，评论580，完读率43%',
      adaptScene: '适合婆媳赛道、原生家庭赛道的仿写，核心冲突=经济控制+偏心',
      createdAt: '2026-07-28'
    },
    {
      id: 'd2', title: '重生后我不再当圣母', platform: '番茄', genre: '重生纠错',
      wordCount: 11000, sectionCount: 14,
      corePlot: '女主重生回到被道德绑架的前世关键节点，不再隐忍，一步步拆穿身边伪善之人，完成逆袭。',
      performance: '番茄首推，首日阅读8万+，加书架3200+',
      adaptScene: '重生赛道+打脸赛道的标准仿写框架，情绪曲线教科书级别',
      createdAt: '2026-07-25'
    },
  ],
  openings: [
    {
      id: 'd1', type: '知乎提问式', title: '婆媳·养老金追问式开篇',
      formula300: '第一句用提问式钩子（"你见过把退休金全给小叔子的婆婆吗？"），第二句补充悬念细节，第三句抛出矛盾核心，第四句设置留人悬念。整体300字内完成：钩子+悬念+情绪锚点+留人。',
      hookTemplate: '"婆婆把退休金卡交给我那天，笑着说以后靠我养老。我感动了三秒，直到我发现卡里只剩83块。"——首屏第一句直接制造信息差和情绪冲击。',
      prosCons: '优点：提问式开篇天然带互动感，读者容易代入；缺点：用多了会套路化，需要每次换角度提问。',
      avoidList: '1.不要用过于夸张的提问；2.提问后2句内必须给出悬念锚点；3.前50字不要出现太多人物，聚焦一个核心矛盾。',
    },
    {
      id: 'd2', type: '番茄冲突式', title: '冲突·当众揭穿式开篇',
      formula300: '第一句直接进入冲突现场（对话+动作），第二句拉高情绪张力，第三句暗示反转即将到来，第四句用悬念钩子留人。300字内制造：冲突+张力+反转预告+留人。',
      hookTemplate: '"你说这房子有你一半？"小叔子攥着房产证，婆婆站在他身后不说话。我笑了，从包里掏出一份公证书。',
      prosCons: '优点：冲突前置，节奏快，番茄读者最吃这套；缺点：如果后续反转不够强，容易翻车。',
      avoidList: '1.开篇冲突不能假大空，要有具体利益冲突；2.第一句不要超过40字；3.钩子要和后文反转紧密关联。',
    },
    {
      id: 'd3', type: '小程序悬念式', title: '悬念·倒计时式开篇',
      formula300: '第一句用悬念制造紧迫感，第二句补充关键信息差，第三句暗示危险/转折临近，第四句设置"接下来会怎样"的留人点。',
      hookTemplate: '三天后婆婆生日宴，全家都会到场。而我手里的那份证据，会在那一刻当众亮出来。',
      prosCons: '优点：悬念感强，适合小程序短篇节奏；缺点：如果倒计时过长读者会流失。',
      avoidList: '1.悬念不能太虚，要有具体的"事件预告"；2.不要在开篇剧透太多；3.第一段结尾必须留钩子。',
    },
  ],
  topics: [
    {
      id: 'd1', track: '婆媳家庭', title: '婆婆偏心小叔子·退休金争夺战',
      formula: '偏心设定→隐忍积累→证据出现→当众打脸→婆婆醒悟/不醒悟二选一',
      conflictTpl: '经济控制权+偏心分配+道德绑架=核心三角冲突',
      plots: '1.婆婆暗中转移财产给小叔子；2.儿媳发现端倪但被道德绑架；3.关键证据出现（转账记录/证人）；4.当众对峙打脸；5.婆婆态度转变或不转变',
      ideas: '退休金争夺战、房产证争夺、丧偶后婆婆要搬来住、婆婆帮小叔子贷款儿媳被追债',
      painPoints: '读者痛点：被偏心对待的委屈、经济被控制的愤怒、道德绑架的窒息感。爽点：当众打脸、经济独立、撕破伪善面具。',
    },
    {
      id: 'd2', track: '重生纠错', title: '重生后不再当圣母·步步拆局',
      formula: '前世被害记忆→重生关键节点→拒绝重蹈覆辙→步步布局→终极打脸',
      conflictTpl: '前世记忆优势vs当下道德绑架=信息差驱动冲突',
      plots: '1.重生到关键被坑节点；2.做出与前世相反的选择；3.布局收集证据；4.逐步拆穿伪善之人；5.终极当众打脸',
      ideas: '重生后不当扶弟魔、重生后不嫁凤凰男、重生后不当工具人、重生后抢回自己的一切',
      painPoints: '读者痛点：前世窝囊憋屈。爽点：带着记忆开挂、每一步都比前世做得好、终极复仇。',
    },
  ],
  characters: [
    {
      id: 'd1', type: '飒爽清醒女主', name: '清醒型女主A版·不内耗不圣母',
      surface: '外表温和但有底线，说话不带脏字但句句到位，不主动挑事但被惹了绝不忍。',
      deep: '内核是极度的自我价值确认——不寻求他人认可，不被道德绑架，知道自己要什么。',
      contrast: '表面温和vs骨子里的狠；看似退让vs实则在布局；嘴上说没关系vs行动上绝不吃亏。',
      entrance: '最好用一个"小事上的清醒"出场——比如面对婆婆的道德绑架，微笑着说"好呀"然后做了一件让对方傻眼的事。',
      function: '承担"读者代入感"功能——她是读者想成为的人，她的每一次清醒操作都给读者带来爽感。',
      avoidPoints: '1.不要写成无脑强势/无理取闹；2.清醒不等于没有感情；3.不要让她永远赢得太轻松，要有拉扯。',
    },
    {
      id: 'd2', type: '伪善白月光', name: '白月光B版·道德高地型',
      surface: '人前永远温柔体贴、善解人意、站在道德制高点说话，让所有人都觉得她好。',
      deep: '内核是极度自私——用道德绑架操控他人，借"为你好"之名行控制之实。',
      contrast: '人前温柔vs人后阴狠；看似退让vs实则在算计；嘴上说为你好vs行动在坑你。',
      entrance: '最好在女主和反派正面冲突时出现，以"和事佬"姿态出现，实则拉偏架。',
      function: '承担"伪善揭穿"功能——她的存在让打脸更有层次感，揭穿她的伪善是最大的爽点。',
      avoidPoints: '1.伪善不能太明显，要让读者也一度觉得她好；2.她的算计要有逻辑；3.被揭穿时要让她自己挖坑自己跳。',
    },
    {
      id: 'd3', type: '道德绑架长辈', name: '道德绑架长辈C版·亲情勒索型',
      surface: '开口闭口"一家人""血浓于水""你都这么大的人了"，用长辈身份压人。',
      deep: '内核是用亲情关系作为控制工具，本质是不愿放弃权力和掌控感。',
      contrast: '对弱势方强势vs对强势方讨好；嘴上说公平vs行动偏心；表面慈爱vs暗里算计。',
      entrance: '最好在家庭聚餐/节日场景出场，一上来就用"为你好"绑架女主。',
      function: '承担"压力制造"功能——她的存在让女主的处境更难，打脸她时爽感加倍。',
      avoidPoints: '1.不要写成纯工具人反派，要有自己的逻辑和软肋；2.被打脸后可以有转变弧光；3.不能太脸谱化。',
    },
  ],
  structure: [
    {
      id: 'd1', title: '万字三幕式·12节标准框架', structureType: '三幕式', wordRange: '8000-12000字',
      ratio: '第一幕（建置·20%）：1600-2400字，3节；第二幕（对抗·60%）：4800-7200字，7节；第三幕（结局·20%）：1600-2400字，2节',
      rhythm: '每节必有：1个独立冲突（本节核心矛盾）+ 节末悬念（留人钩子）。第1节：矛盾导入+悬念。第2-3节：矛盾升级+小反转。第4-8节：拉扯反复+伏笔铺垫。第9-10节：高潮爆发+大反转。第11节：打脸收束。第12节：收尾留白。',
      foreshadow: '前3节埋3条伏笔线，第4-8节暗收1条，第9-10节集中回收2条。伏笔回收密度：每2节至少收1条。',
      reversal: '小反转每2-3节1次，大反转全文2次（第6节左右1次中转，第10节1次终转）。反转之间间隔不少于2节。',
      emotionCurve: '憋屈（1-3节）→拉扯（4-6节）→爆发（7-8节）→打脸（9-10节）→收尾（11-12节）。情绪曲线持续上扬，每个转折点必须有明显的情绪峰值。',
    },
  ],
  analysis: [
    {
      id: 'd1', title: '婆婆的退休金去哪了', platform: '知乎', genre: '婆媳家庭',
      mainPlot: '大梗：退休金去向之谜→偏心真相→当众打脸。小梗：小叔子赌债→婆婆的道德绑架→邻居证人→转账记录。',
      conflict: '核心矛盾：经济控制权+偏心分配+道德绑架。三角冲突结构：婆婆（施害者）vs儿媳（受害者+反击者）vs小叔子（既得利益者）。',
      hooks: '第1节：退休金消失悬念钩；第3节：小叔子出现信息差钩；第6节：发现转账记录反转钩；第9节：生日宴当众对峙高潮钩；第11节：婆婆态度转变留白钩。',
      climax: '爽点：当众亮出转账记录打脸；虐点：婆婆说"我就是偏心，怎么了"的瞬间。情绪峰值在生日宴对峙戏。',
      rhythmReview: '优点：节奏紧凑，每节都有钩子，信息释放节奏好。缺点：中段拉扯稍长（第4-5节），可以压缩。',
      logicHoles: '1.邻居怎么知道转账细节？需要铺垫；2.小叔子赌债金额和退休金金额对不上，需要调整数字。',
      viralReason: '爆火原因：1.婆媳矛盾是全民级共鸣话题；2.经济控制+偏心的双重痛点精准命中；3.当众打脸的爽感极强；4.知乎提问式标题自带流量。',
      adaptPlan: '对标仿写：保留"经济控制+偏心+当众打脸"骨架，换设定为"房产分配"或"遗产争夺"，换人物关系为"姐妹争产"或"岳母vs女婿"。',
      rewrite: '换汤不换药：核心框架=隐忍→发现→证据→当众打脸。换赛道：从婆媳换成职场（上司偏心+当众打脸），从退休金换成项目功劳争夺。',
    },
  ],
  quotes: [
    {
      id: 'd1', category: '开篇抓人金句', content: '婆婆把退休金卡交给我那天，笑着说以后靠我养老。我感动了三秒，直到我发现卡里只剩83块。',
      scene: '婆媳赛道开篇', tags: ['婆媳','经济控制','悬念'], notes: '信息差+情绪冲击，适合知乎提问式开篇变体。',
    },
    {
      id: 'd2', category: '对峙打脸对话', content: '"你说这房子有你一半？"小叔子攥着房产证。我笑了，从包里掏出一份公证书。"有，但不是你想的那种有。"',
      scene: '房产争夺打脸戏', tags: ['打脸','反转','对话'], notes: '动作配合对话，反转藏在物件里。',
    },
    {
      id: 'd3', category: '反转点睛金句', content: '原来从头到尾，我在意的不是那笔钱，是她从来没把我当一家人。而我，也终于不必再演了。',
      scene: '情绪转折/反转点', tags: ['情绪','转折','收束'], notes: '适合放在大反转后的情绪收束段。',
    },
    {
      id: 'd4', category: '结尾收口金句', content: '后来婆婆再没提过退休金的事。过年她给我夹菜的时候，我笑着说了声谢谢。有些仗，打赢了就够了，不必再提。',
      scene: '婆媳文结尾收口', tags: ['结尾','留白','和解'], notes: '打完脸后的余韵收束，适合留白型结局。',
    },
  ],
  endings: [
    {
      id: 'd1', type: '爽文打脸结局', title: '打脸式·当众揭穿型结局',
      template: '最后2节：1.反派得意忘形（以为赢了）；2.女主亮出底牌（证据/证人/反转）；3.当众打脸（围观者震惊）；4.反派崩溃/求饶；5.女主一句话收束。',
      fastEnd: '最后800字：1句过渡→1段亮牌→1段打脸→1段反派反应→1句金句收束。不拖泥带水，打完就走。',
      avoidList: '1.打脸不要拖太长，3段内完成；2.反派不能莫名其妙投降，要有逻辑；3.不要在结尾再开新坑。',
      callback: '回收到第1节埋的退休金悬念、第3节小叔子的赌债伏笔、第6节的转账记录。三线齐收。',
    },
    {
      id: 'd2', type: '遗憾留白结局', title: '留白式·意难平型结局',
      template: '最后2节：1.核心冲突解决但代价已付；2.女主获得胜利但失去了一些东西；3.一个留白画面结尾；4.用一句话点题。',
      fastEnd: '最后500字：1段过渡→1段余韵→1句点题。留白结局字数要少，点到即止。',
      avoidList: '1.留白不等于没写完，要有情绪余韵；2.不要强行煽情；3.留白画面要和前文有呼应。',
      callback: '回收到前文女主的一个小习惯/小物件/一句话，在结尾用同款意象做呼应。',
    },
  ],
  compliance: [
    {
      id: 'd1', platform: '知乎', title: '知乎·婆媳类敏感剧情避雷',
      redLines: '1.不能直接攻击老年人群体；2.不能煽动性别对立；3.不能涉及真实社会事件影射；4.不能过度渲染暴力。',
      taboo: '1.婆婆纯恶无逻辑的设定容易被举报；2.丈夫完全失能的设定争议大；3.涉及法律程序的剧情需要准确。',
      limitTraps: '1.标题太极端会限流（如"恶婆婆去死"）；2.开头纯负能量会降推荐；3.评论互动差会影响分发。',
      retention: '1.开篇300字必须有钩子；2.每节末尾留悬念；3.善用加粗/分段提升阅读体验；4.关键情绪点用短句。',
      checklist: '□标题不极端 □开篇有钩子 □无攻击特定群体 □无法律硬伤 □每节有悬念 □结尾有收束 □无错别字',
      caseStudy: '拒稿案例：标题"恶毒婆婆不得好死"→改为"婆婆的退休金去哪了"后过稿。原因：原标题攻击性过强。',
    },
    {
      id: 'd2', platform: '番茄', title: '番茄·婆媳家庭类审核红线',
      redLines: '1.不能涉及真实政治人物；2.不能渲染极端暴力血腥；3.不能过度描写自残自杀；4.不能涉及未成年不当内容。',
      taboo: '1.家暴剧情需要谨慎处理；2.婚内出轨不能美化；3.涉及赌博毒品需要负面定调。',
      limitTraps: '1.前3章留存率决定推荐量；2.章节标题太长会影响点击；3.更新不规律会掉推荐。',
      retention: '1.每章末尾卡在悬念处；2.前3章节奏要快；3.善用"本章说"功能引导评论；4.关键情节放章节末尾。',
      checklist: '□前3章节奏快 □每章末有悬念 □无敏感内容 □无错别字 □字数达标 □章节标题简洁',
      caseStudy: '拒稿案例：前3章铺垫太长被低留存→改为第1章直接冲突开场后留存率提升25%。',
    },
    {
      id: 'd3', platform: '小程序', title: '小程序·短篇审核与限流避雷',
      redLines: '1.不能涉及真实品牌/公司名；2.不能有诱导分享的强制行为；3.不能涉及医疗/法律专业建议；4.不能有过度恐怖内容。',
      taboo: '1.灵异类需要淡化到"巧合"解释；2.涉及疾病需要模糊处理；3.职场类不能影射真实公司。',
      limitTraps: '1.标题字数控制在15字以内；2.首屏加载速度影响留存；3.分享卡片标题决定裂变。',
      retention: '1.开篇50字内出冲突；2.每800-1000字一个反转点；3.善用换行和短段提升手机阅读体验；4.关键悬念卡在分享点。',
      checklist: '□标题15字内 □首屏有冲突 □每段不超3行 □无敏感内容 □分享点有悬念 □结尾有引导',
      caseStudy: '拒稿案例：灵异类直接写鬼→改为"可能是梦游"后过稿。原因：小程序对灵异类审核严格。',
    },
  ],
  conflicts: [
    {
      id: 'd1', type: '家庭矛盾', title: '婆婆偷翻儿媳抽屉被发现',
      content: '婆婆趁儿媳不在家偷偷翻找抽屉，被提前回家的儿媳撞见。儿媳没有当场翻脸，而是用一种"我什么都没看见"的方式处理，然后在后续剧情中逐步收网。',
      scene: '婆媳家庭赛道·冲突升级节点', tags: ['婆媳','偷翻','经济控制'], notes: '这个桥段可以用来制造"隐忍→爆发"的情绪铺垫。',
    },
    {
      id: 'd2', type: '职场矛盾', title: '同事偷了你的方案当自己的汇报',
      content: '女主花一周做的方案被同事偷走抢先汇报，女主没有当场翻脸，而是收集证据后在关键会议上当众揭穿。',
      scene: '职场逆袭赛道·打脸节点', tags: ['职场','方案偷窃','当众打脸'], notes: '经典职场打脸桥段，可以和婆媳赛道的"偷翻"做平行处理。',
    },
    {
      id: 'd3', type: '情绪拉扯片段', title: '她说"都是一家人"的那一刻',
      content: '当女主试图反抗时，对方说出"都是一家人，你至于吗？"——这句话精准踩中道德绑架的情绪点，让女主一时语塞。后续女主找到反击方式。',
      scene: '所有赛道·情绪拉扯节点', tags: ['道德绑架','情绪拉扯','一句话'], notes: '可以反复变形使用，换不同场景说出类似的话。',
    },
  ],
  hotspots: [
    {
      id: 'd1', subCategory: '当日热点日报', title: '婆婆把存款全给小儿子，大儿媳起诉追回',
      source: '微博', sourceLink: 'https://weibo.com/search?q=婆婆存款小儿子',
      fullText: '近日，某地法院审理了一起赠与合同纠纷案。婆婆王某瞒着大儿媳李某，将夫妻共同存款50万元转给小儿子还赌债。李某发现后，以夫妻共同财产未经双方同意为由起诉，法院最终判决赠与部分无效，小儿子需返还35万元。\n\n案件引发网友热议，有人认为婆婆有权处置自己的份额，也有人认为大儿媳维权正确。律师提醒：夫妻共同财产单方大额赠与可能无效。',
      summary: '婆婆瞒着大儿媳将50万存款转给小儿子还债，大儿媳发现后起诉，法院判决赠与无效。',
      emotionTag: '愤怒、不忿、打脸、大快人心',
      conflict: '经济控制权+偏心分配+法律边界=核心三角冲突',
      novelCore: '婆婆暗中转移财产给小儿子，儿媳发现后收集证据，在家庭聚会当众揭穿并拿出法律文件追回。',
      adaptTrack: '婆媳家庭',
      titleTemplates: '知乎：婆婆把50万给了小叔子，我拿出一份公证书\n番茄：婆婆偷给小叔子50万，我让她一分都拿不回\n小程序：婆婆的50万去哪了',
    },
    {
      id: 'd2', subCategory: '历史热点存档', title: '老人遗嘱把房产给照顾自己的保姆',
      source: '头条', sourceLink: 'https://www.toutiao.com/search/老人遗嘱房产保姆',
      fullText: '某市一位独居老人去世后，子女发现老人将名下唯一房产遗赠给照顾自己多年的保姆张某。子女不满，起诉要求确认遗嘱无效。法院审理后查明，遗嘱系老人真实意思表示，有见证人和录像佐证，最终驳回子女诉讼请求。\n\n据了解，老人晚年子女鲜少探望，保姆张某照顾老人起居五年有余。老人曾多次向邻居表示"比亲儿女还亲"。',
      summary: '老人将房产遗赠给照顾自己多年的保姆，子女起诉要求确认遗嘱无效，法院最终支持了遗嘱效力。',
      emotionTag: '讽刺、打脸、反转、情感复杂',
      conflict: '血缘关系vs真实付出=价值观冲突',
      novelCore: '子女多年不探望老人，老人将房产遗赠给保姆。子女来闹，保姆亮出遗嘱和录像。',
      adaptTrack: '原生家庭',
      titleTemplates: '知乎：老人把房子给了保姆，儿女来闹时她拿出一段录像\n番茄：爸妈的房子给了保姆，我笑了\n小程序：遗嘱上写着保姆的名字',
    },
  ],
};
